services:


  postgresql-dev:
    container_name: postgresql-dev
    image: postgres:17
    ports:
      - 5432:5432

    restart: unless-stopped 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aa

    volumes:
      - postgresql-dev:/var/lib/postgresql/data

volumes:
  postgresql-dev: